// Ported from v2.5-beta-1-modern/resource.h.
// Qt replacement keeps original numeric command IDs where they are used by code.

#pragma once

#define IDR_MAINFRAME                   128
#define IDS_BANMESG                     134
#define IDS_NOTINROOM                   131
#define IDS_NOTINANYROOM                146
#define IDS_DFLTAWAYMSG                 137
#define IDS_ROOMNEEDSFOCUS              208
#define IDS_CONFIRMAWAY                 206
#define IDS_KICKMSG_SYNTAX              230
#define IDS_KILLMSG_SYNTAX              231
#define IDS_SYNTAXPREFIX                232
#define IDS_AT_NICKNAME                 233
#define IDS_AT_NICKMASK                 234
#define IDS_AT_CHANNEL                  235
#define IDS_AT_TOPIC                    236
#define IDS_AT_REASON                   237
#define IDS_AT_MESSAGE                  238
#define IDS_AT_MAXMEMBER                239
#define IDS_AT_CHANNELFLAGS             240
#define IDS_AT_PASSWORD                 241
#define IDS_AT_SERVER                   242
#define IDS_AT_NETWORK                  243
#define IDS_AT_SOUND                    244
#define IDS_AT_USERFLAGS                245
#define IDS_AT_PROPNAME                 246
#define IDS_AT_PROPVALUE                247
#define IDS_AT_SPACEMULTIPLE            254
#define IDB_SAY_BAR                     180
#define IDD_ROOMLIST                    186
#define IDD_EDITRULE                    184
#define IDD_RULESPAGE                   188
#define IDD_KICK                        195
#define IDD_SETUPDIALOG                 177
#define IDD_SETTINGSPAGE                189
#define IDD_PERSONALPAGE_IRC            190
#define IDD_CHARACTERPAGE               191
#define IDD_BACKGROUNDPAGE              192
#define IDD_CHANNEL                     198
#define IDD_CHANNELPROP                 199
#define IDD_BAN                         200
#define IDD_INVITE                      201
#define IDD_TEXTFONTPAGE_IRC            224
#define IDD_COMICS_VIEW                 1545
#define IDR_TEXTTOOLBAR                 200
#define IDR_USERTOOLBAR                 201
#define IDR_NMUSERTOOLBAR               202
#define IDR_HAPPY                       210
#define IDR_LAUGH                       211
#define IDR_SHOUT                       212
#define IDR_ANGRY                       213
#define IDR_SAD                         214
#define IDR_SCARED                      215
#define IDR_BORED                       216
#define IDR_COY                         217
#define IDR_FORMATTING                  218
#define IDR_STATUSVIEW                  219
#define IDB_WHISPER_BAR                 260
#define IDR_WHISPERACCEL                281
#define IDR_RTFACCEL                    282
#define IDI_WHISPER                     285
#define IDI_CONNECT_SRV                 287
#define IDI_CONNECT_NET                 288
#define IDD_PASSWORD                    289
#define IDD_USERLIST                    225
#define IDR_TOOLBARCONTEXT              291
#define IDD_CHANNELCREATE               1547
#define IDD_AUTOMATION_PAGE             1546
#define IDD_MOTD                        261
#define IDD_INVITATION                  270
#define IDD_AWAYDLG                     268
#define IDB_STOPPED                     271
#define IDD_ADVANCEDEVENTPARAMS         274
#define IDD_RULESETSPAGE                275
#define IDD_ADDTOSETS                   276
#define IDD_RENAMELOADEDSET             277
#define IDD_RENAMESET                   278
#define IDD_ADVANCEDRULESETTINGS        283
#define IDD_CREATESET                   290
#define IDD_WHISPERBOX                  1544
#define IDD_SERVERSPAGE                 1552
#define IDOK                            1
#define IDCANCEL                        2
#define IDYES                           6
#define IDNO                            7
#define IDC_BANTOO                      1011
#define IDC_SHOW_MOTD                   1011
#define IDC_SEARCH_DESCRS               1011
#define IDC_REGISTERED_ONLY             1012
#define IDC_GOTO                        1038
#define IDC_DELETE_TAB                  1038
#define IDC_BANNED_USERS                1037
#define IDUNBAN                         1038
#define IDC_TOPIC_EDIT                  1042
#define IDC_ROOMLIST                    1045
#define IDC_RESET_LIST                  1046
#define IDC_USERSEARCH_IDENTITY         1062
#define IDC_REASON                      1052
#define IDC_USERSEARCH_ROOM             1063
#define IDC_ROOM_CAPTION                1065
#define IDC_SEARCH_TIME                 1066
#define IDC_MIN_MEMBERS                 1068
#define IDC_BANTOO_NAME                 1068
#define IDC_MESSAGE                     1068
#define IDC_MAX_MEMBERS                 1070
#define IDC_KICKMSG                     1072
#define IDC_CLOSE_ROOMLIST              1076
#define IDC_NEWROOM                     1079
#define IDC_LISTMEMBERS                 1080
#define IDC_INVITEES                    1086
#define IDC_USERSEARCH_NICK             1089
#define IDC_CLOSE_USERLIST              1090
#define IDC_INVITE_FROM_LIST            1098
#define IDC_MESSAGE_FROM_LIST           1099
#define IDC_USERLIST                    1100
#define IDC_SEARCH_EDIT                 1101
#define IDC_USERSEARCH_ALL              1102
#define IDC_SEARCH_LABEL                1103
#define IDC_ROOM_LABEL                  1104
#define IDC_ROOM_EDIT                   1105
#define IDC_SPIN_MIN                    1118
#define IDC_SPIN_MAX                    1119
#define IDC_EDITPOS                     1126
#define IDBAN                           1127
#define IDC_BANMESG                     1128
#define IDC_AWAYMSG                     1136
#define IDC_JOINROOM                    1144
#define IDC_GROUP0                      1166
#define IDC_KEY                         1037
#define IDC_ADD_MACRO                   1038
#define IDC_MACRORICHEDIT               1068
#define IDC_GREETINGMESG                1069
#define IDC_NOGREETING                  1091
#define IDC_WHISPERGREETING             1092
#define IDC_SAYGREETING                 1093
#define IDC_MACRONAME                   1109
#define IDC_DELETE_MACRO                1111
#define IDC_AUTOIGNORE                  1139
#define IDC_MESGCOUNTSPIN               1140
#define IDC_INTERVALSPIN                1141
#define IDC_MESGCOUNT                   1142
#define IDC_INTERVAL                    1143
#define IDC_GROUP2                      1164
#define IDC_GROUP1                      1165
#define IDC_LSTRULES                    1169
#define IDC_ADDRULE                     1170
#define IDC_EDITRULE                    1171
#define IDC_DELETERULE                  1172
#define IDC_MOVEUP                      1173
#define IDC_MOVEDOWN                    1174
#define IDC_LBLEP0                      1178
#define IDC_CMBEP0                      1179
#define IDC_LBLEP1                      1180
#define IDC_CMBEP1                      1181
#define IDC_LBLEP2                      1182
#define IDC_CMBEP2                      1183
#define IDC_CMBEVENTS                   1184
#define IDC_CMBACTIONS                  1185
#define IDC_LBLAP0                      1186
#define IDC_CMBAP0                      1187
#define IDC_LBLAP1                      1188
#define IDC_CMBAP1                      1189
#define IDC_LBLAP2                      1190
#define IDC_CMBAP2                      1191
#define IDC_LBLPARAMDESC                1192
#define IDC_LBLEP                       1194
#define IDC_LBLAP                       1195
#define IDC_RTFAP0                      1200
#define IDC_RTFAP1                      1201
#define IDC_RTFAP2                      1202
#define IDC_LSTSETS                     1210
#define IDC_CHKSUBRULES                 1225
#define IDC_BTNADVANCED                 1226
#define IDC_CHKMATCHCASE                1227
#define IDC_CHKMATCHWORD                1228
#define IDC_LSTRULESETS                 1229
#define IDC_BTNLOADSET                  1230
#define IDC_BTNSAVESET                  1231
#define IDC_DELETERULESET               1233
#define IDC_MOVERULESETUP               1234
#define IDC_MOVERULESETDOWN             1235
#define IDC_CREATERULESET               1236
#define IDC_ADDTORULESETS               1239
#define IDC_DUPLICATERULE               1240
#define IDC_ALSTSETS                    1241
#define IDC_ALSTRULES                   1243
#define IDC_BTNOVERWRITERULESET         1244
#define IDC_RENAMEDRULESET              1245
#define IDC_BTNRENAMELOADEDRULESET      1246
#define IDC_RULESETCONFLICT             1247
#define IDC_RENAMERULESET               1248
#define IDC_RENAMEDSET                  1249
#define IDC_ADVANCEDRULE                1251
#define IDC_RULEOCC                     1253
#define IDC_RULEOCCSPIN                 1254
#define IDC_RULEINT                     1255
#define IDC_RULEINTSPIN                 1256
#define IDC_CMBAPSD                     1314
#define IDC_CMBEPNS                     1315
#define IDC_CMBAPNS                     1327
#define IDC_CREATEDSET                  1328
#define IDC_RULEDELAY                   1330
#define IDC_DELAYSPIN                   1331
#define IDC_IGNORE                      1168
#define IDS_ERR_RAWJOINCREATE           61239
#define IDS_ERR_NOMOTD                  61241
#define IDS_ERR_NOSUCHCHANNELANYMORE    61240
#define IDS_BLANKNICK                   221
#define ID_ERR_BAD_NICK                 63007
#define ID_ERR_DUPED_NICK               63008
#define ID_PASSWORD_PROMPT              63086
#define IDS_BAD_PASSWORD                63143
#define ID_ERR_BADCHANNELNAME           63082
#define IDS_MUSTBE_CONNECTED            63099
#define IDS_NOSLASH_COMMANDS            63101
#define IDS_PRIVMSG_SYNTAX              63181
#define IDS_ME_SYNTAX                   63184
#define IDS_SOUND_SYNTAX                63185
#define IDS_GETTOPIC_SYNTAX             63187
#define IDS_SETTOPIC_SYNTAX             63188
#define IDS_PROPGET_SYNTAX              63189
#define IDS_PROPSET_SYNTAX              63190
#define ID_RL_ROOM_LABEL                63046
#define ID_RL_ROOM_WIDTH                63047
#define ID_RL_NUSERS_LABEL              63048
#define ID_RL_NUSERS_WIDTH              63049
#define ID_RL_DESCR_LABEL               63050
#define ID_RL_DESCR_WIDTH               63051
#define IDS_NUM_ROOMS                   63062
#define IDS_KICKREASON                  63068
#define ID_JOIN_OFFER                   63090
#define ID_UL_REALNAME_LABEL            32992
#define ID_UL_REALNAME_WIDTH            32993
#define ID_UL_ROOM_LABEL                32994
#define ID_UL_ROOM_WIDTH                32995
#define ID_UL_NICK_LABEL                63118
#define ID_UL_NICK_WIDTH                63119
#define ID_UL_IDENT_LABEL               63120
#define ID_UL_IDENT_WIDTH               63121
#define IDS_NUM_USERS                   63122
#define IDS_OUTCHANNEL_INVITE           63123
#define IDS_INVITE_CONF                 63124
#define IDS_SEARCH_TIME                 63125
#define IDS_OP_ANY                      63170
#define IDS_OP_EQUALS                   63171
#define IDS_OP_CONTAINS                 63172
#define IDS_OP_STARTSWITH               63173
#define IDS_OP_ENDSWITH                 63174
#define IDS_NOTIF_NICKWIDTH             63175
#define IDS_NOTIF_IDENTWIDTH            63176
#define IDS_NOTIF_REALWIDTH             63177
#define IDS_NOTIF_ROOMWIDTH             63178
#define IDS_NOTIF_TIMELABEL             63179

#define IDB_OLDNEW                      150
#define IDB_CONNECT                     151
#define IDB_INACTIVE                    272
#define IDB_ACTIVE                      273
#define IDD_NOTIFICATIONS               279
#define IDD_NOTIFICATIONUSERS           284
#define IDI_NOTIF                       286

#define IDC_MODERATED                   1012
#define IDC_TOPICANYONE                 1013
#define IDC_NICKNAME                    1018
#define IDC_SERVER                      1019
#define IDC_REALNAME                    1021
#define IDC_CHANNEL                     1023
#define IDC_CONNECTONLY                 1063
#define IDC_TAB1                        1104
#define IDC_SAYPOSITION                 1106
#define IDC_IGNORE_WBOX                 1107
#define IDC_PASSWORD                    1110
#define IDC_PASSWORD_GIVEN              1112
#define IDC_CHANNELNAME                 1113
#define IDC_TOPIC_RICHEDIT              1129
#define IDC_SERVERLIST                  1157
#define IDC_SERVERS_LABEL               1158
#define IDC_BACKGROUND_COPYRIGHT        1221
#define IDC_AVATAR_COPYRIGHT            1222
#define IDC_LSTNOTIFS                   1257
#define IDC_DELETENOTIF                 1258
#define IDC_ADDNOTIF                    1259
#define IDC_CMBNICKOP                   1260
#define IDC_CMBUSEROP                   1261
#define IDC_CMBHOSTOP                   1262
#define IDC_NICKARG                     1263
#define IDC_USERARG                     1264
#define IDC_HOSTARG                     1265
#define IDC_CMBNETARG                   1266
#define IDC_MODIFYNOTIF                 1267
#define IDC_LSTNOTIFICATIONUSERS        1274
#define IDC_NOTIFWHISPER                1276
#define IDC_NOTIFINVITE                 1277
#define IDC_NOTIFJOIN                   1278
#define IDC_DEFINENOTIF                 1279
#define IDC_NOTIFUPDATE                 1280
#define IDC_NOTIFCLEAR                  1281
#define IDC_CLOSE_NOTIFUSERS            1282
#define IDC_NOTIFTOPLABEL               1284
#define IDC_NOTIFCOUNT                  1285
#define IDC_NOTIFTIME                   1286
#define IDC_SRVGROUP_COMBO              1283
#define IDC_SRVGROUP_ADD                1284
#define IDC_SRVGROUP_REMOVE             1285
#define IDC_SERVER_ADD                  1296
#define IDC_SERVER_REMOVE               1297
#define IDC_SERVER_SECURITY             1298
#define IDC_SERVER_PORT                 1304
#define IDC_SERVER_PORT_LABEL           1305
#define IDC_SRVCONNECT_NOPWD            1306
#define IDC_SRVCONNECT_PWD              1307
#define IDC_SRV_USERNAME                1308
#define IDC_SRV_PASSWORD                1309
#define IDC_SRV_REMEMBER_PWD            1310
#define IDC_SRV_PASSWORD_LABEL          1316
#define IDC_SRV_USERNAME_LABEL          1317
#define IDC_SERVER_PORT_NW              1319
#define IDC_REMEMBER_PASSWORD           1320
#define IDC_USERNAME                    1323
#define IDC_SERVERNAME                  1326
#define IDC_NOPWD_MESSAGE               1334

#define IDS_PREDEFGROUP_MS              213
#define IDS_PREDEFGROUP_MSN             214
#define IDS_UNASSOCIATED_GROUP          215
#define IDS_DELETEGROUP_WARNING         216
#define IDS_PORTNUM_ERROR               217
#define IDS_DEFAULT_SERVERLIST          63024

#define ID_ACTIONS_SAY                  32783
#define ID_ACTIONS_THINK                32784
#define ID_BODYCONTEXT_FREEZE           32850
#define ID_BODYCONTEXT_SENDEXPRESSION   32852
#define ID_ACTIONS_WHISPER              32878
#define ID_HELP_TOPICS                  32881
#define ID_VIEW_LIST                    32882
#define ID_VIEW_ICON                    32883
#define ID_VIEW_STATUS_BAR              32886
#define ID_EDIT_DELETE                  32889
#define ID_EDIT_SELECTALL               32890
#define ID_FAVORITES_ADDTOFAVORITES     32892
#define ID_FAVORITES_OPENFAVORITES      32893
#define ID_FILE_CREATESHORTCUT          32895
#define ID_MEMBER_GETINFO               32899
#define ID_MEMBER_IGNORE                32900
#define ID_SEND_ACTION                  32901
#define ID_VIEW_TOOLBAR_MAIN            32902
#define ID_VIEW_TOOLBAR_MEMBER          32903
#define ID_VIEW_TOOLBAR_TEXT            32904
#define ID_VIEW_COMICS                  32909
#define ID_VIEW_TEXT                    32910
#define ID_CHATROOM_LIST                32911
#define ID_VIEW_OPTIONS                 32912
#define ID_VIEW_AUTOMATIONS             32913
#define ID_ADMINISTRATOR_KICK           32916
#define ID_SESSION_NEWROOM              32919
#define ID_SESSION_LEAVE                32920
#define ID_SESSION_CONNECT              32921
#define ID_SESSION_DISCONNECT           32922
#define ID_ADDTONOTIFICATIONS           32925
#define ID_CHANNELPROPS                 32926
#define ID_ADMIN_BGRNDSYNC              32927
#define ID_ADMIN_BAN                    32928
#define ID_MAKEADMIN                    32930
#define ID_MAKESPEAKER                  32931
#define ID_MAKESPECTATOR                32932
#define ID_INVITE                       32933
#define ID_GETIDENTITY                  32935
#define ID_SETFONT                      32936
#define ID_GET_VERSION                  32937
#define ID_PLAY_SOUND                   32938
#define ID_PING_USER                    32939
#define ID_GET_LOCALTIME                32940
#define ID_USER_LIST                    32941
#define ID_WHISPERBOX_MLIST             32942
#define ID_MACRO_A1                     32944
#define ID_MACRO_A2                     32945
#define ID_MACRO_A3                     32946
#define ID_MACRO_A4                     32947
#define ID_MACRO_A5                     32948
#define ID_MACRO_A6                     32949
#define ID_MACRO_A7                     32950
#define ID_MACRO_A8                     32951
#define ID_VIEW_MACROS                  32954
#define ID_WHISPER_ACTION               32965
#define ID_WHISPER_SOUND                32966
#define ID_MEMBER_GETCHAR               32970
#define ID_ROOM_CREATEROOM              32971
#define ID_SEND_EMAIL                   32974
#define ID_VISIT_HOMEPAGE               32975
#define ID_START_NETMEETING             32976
#define ID_SEND_FILE                    32980
#define ID_HELP_FREESTUFF               32981
#define ID_HELP_PRODUCTNEWS             32982
#define ID_HELP_FAQ                     32983
#define ID_HELP_ONLINESUPPORT           32984
#define ID_HELP_BESTOFWEB               32985
#define ID_HELP_SEARCHTHEWEB            32987
#define ID_HELP_MSHOMEPAGE              32988
#define ID_HELP_RELEASENOTES            32990
#define ID_AWAY_TOGGLE                  32996
#define ID_VIEW_TABBAR                  32998
#define ID_SETCOLOR                     33018
#define ID_SWITCHBOLD                   33019
#define ID_SWITCHITALIC                 33020
#define ID_SWITCHUNDERLINED             33021
#define ID_SWITCHFIXEDPITCH             33022
#define ID_SWITCHSYMBOL                 33023

// Rule resource ranges used by v2.5-beta-1-modern/rules.cpp. The Qt asset
// adapter resolves the corresponding symbolic entries directly from chat.rc.
#define IDS_MISSING_EVENT_PARAM_ERROR0  33030
#define IDS_MISSING_ACTION_PARAM_ERROR0 33050
#define IDS_EVENT_PARAM_DESC0           33070
#define IDS_EVENT_LONG_DESC0            33120
#define IDS_EVENT_SHORT_DESC0           33140
#define IDS_ACTION_PARAM_DESC0          33200
#define IDS_ACTION_LONG_DESC0           33300
#define IDS_ACTION_SHORT_DESC0          33340
#define IDS_KEY_EVENT_PARAM0            33380
#define IDS_KEY_ACTION_PARAM0           33400
#define IDS_EVENTCMBDESC                33435
#define IDS_ACTIONCMBDESC               33436
#define IDS_ERR_FILELINERANGE           33450
#define IDS_ERR_NOBOOLEAN               33451
#define IDS_ERR_NOHIGHLIGHT             33452
#define IDS_ERR_MATCHALL                33453
#define IDS_ERR_RULEDISPLAY             33454
#define IDS_ERR_FLOODING                33455
#define IDS_ERR_NOTIFALREADYEXISTS      33456
#define IDS_LBL_ACTIVATE                33420
#define IDS_ERR_CRS_VERSION             33475
#define IDS_ERR_CRS_FORMAT              33476
#define IDS_ERR_CRS_ACCESSDENIED        33477
#define IDS_ERR_CRS_LOCKVIOLATION       33478
#define IDS_ERR_CRS_DISKFULL            33479
#define IDS_ERR_CRS_LOADGENERIC         33480
#define IDS_ERR_CRS_SAVEGENERIC         33481
#define IDS_ERR_CRS_CONFLICT            33482
#define IDS_ERR_CRS_CONFLICT2           33483
#define IDS_ERR_CRS_SKIPPEDRULES        33484
#define IDS_SAMPLES_RULESET             33499
#define IDS_GENERAL_RULESET             33500
#define IDS_SAMPLES_RULE1               33501
#define IDS_SAMPLES_RULE2               33502
#define IDS_SAMPLES_RULE3               33503
#define IDS_SAMPLES_RULE4               33504
#define IDS_SAMPLES_RULE5               33505
#define IDS_SAMPLES_RULE6               33506
#define IDS_SAMPLES_RULE7               33507
#define ID_TOOLBAR_HELP                 42819
#define ID_TOOLBAR_ADD                  42820
#define ID_TOOLBAR_CUT                  42821
#define ID_TOOLBAR_COPY                 42822
#define ID_TOOLBAR_PASTE                42823
#define ID_TOOLBAR_SHOW                 42824
#define ID_TOOLBAR_MEMBER               42825
#define ID_TOOLBAR_IGNORE               42826
#define ID_TOOLBAR_SAVE                 42827
#define ID_MOTD                         42828
#define ID_VIEW_STATUSWINDOW            42830
#define ID_CLEAR_HISTORY                42831
#define ID_DEFINE_MACRO                 42832
#define ID_VIEW_LOGINNOTIFS             42834
#define ID_WINDOW_TILE_AUTO             42835
#define ID_TURN_OFF_SOUNDS              42836

#define ID_EM_HAPPY                     62446
#define ID_EM_NEUTRAL                   62454
#define ID_EMOTION_IS                   63000
#define ID_STARRING                     63017
#define IDS_HIGHLIGHT_TYPE              63149
#define IDS_AUTOMATIONS                 63071
#define IDS_EMPTYMACRO                  63136
#define IDS_CRS_FILTER                  63145
#define IDS_EVENTS_LABEL                63150
#define IDS_EVENTS_WIDTH                63151
#define IDS_ACTIONS_LABEL               63152
#define IDS_ACTIONS_WIDTH               63153
#define IDS_TEXTFILES                   32816
#define IDS_GET_CHARACTER               209
#define ID_MACRO_A0                     32943
#define ID_MACRO_A9                     32952
